import { Vehicle } from "./Vehicle";
import { Penaltie } from "./Penaltie";
import { Organization } from "./Organization";
import { RealEstate } from "./RealEstate";

export type SearchedPlayer = {
  UID: number;
  username: string;
  usernameRP: string;
  created: Date;
  gold: Date;
  diamond: Date;
  skin: number;
  health: number;
  money: string;
  bankmoney: string;
  online: string;
  lastOnline: Date;
  personal_token: string;
  lastNameChange: Date;
  lastRPNameChange: Date;
  cardPlays: number;
  vehicleLimit: number;
  houseLimit: number;
  premiumPoints: number;
  vehicles?: Vehicle[];
  penalties?: Penaltie[];
  organizations?: Organization[];
  realestates?: RealEstate[];
};
